- name: play level variable
  hosts: local
  connection: local
  vars_files:
  - course_file.yaml

  tasks: # list of tasks
  - name: print course DURATION
    vars:
      COURSE: Ansible
      DURATION: 10HR
    ansible.builtin.debug:
     msg: "Hello {{COURSE}}, Course DURATION: {{DURATION}}, TRAINER is {{TRAINER}} and the STUDENT is {{STUDENT}}"

  - name: print course DURATION
    ansible.builtin.debug:
     msg: "Hello {{COURSE}}, Course DURATION: {{DURATION}}, TRAINER is {{TRAINER}} and the STUDENT is {{STUDENT}}"