- name: ansible datatypes
  hosts: local
  connection: local
  vars:
    COURSE: DevSecOps with AWS
    DURATION: 120DAYS
    IS_LIVE: TRUE
    TOOLS:
      - Linux
      - Shell
      - Ansible
    CONCEPTS:
     CI: Jenkins
     SCRIPTING: "Shell, Ansible, Terraform, Python"

  tasks:
  - name: Printing the Course Details
    ansible.builtin.debug:
     msg: "Course is {{ COURSE }}, Duration is {{ DURATION }}, is Live ? {{ IS_LIVE }}, Tools are {{ TOOLS }}, CONCEPTS are {{ CONCEPTS}}"