- name: functions
  hosts: local
  connection: local
  vars:
    persons: "Kranthi_Kumar,Dileep_Venkata_Prasad,Shiva_Shankar,Surya_Gnanesh,manikanta"
  tasks:
  - name: check undefined variable
    ansible.builtin.debug:
      msg: "Hello, {{ person | default('Kranthi_Kumar') }}"

  - name: print names
    ansible.builtin.debug:
      msg: "Hello {{ persons | split(',') }}"

  - name: convert map into list
    vars:
      course:
        name: ansible
        duration: 10HR
        trainer: sivakumar
        student: kranthikumar
    ansible.builtin.debug:
      msg: "Course Info: {{ course | dict2items  }}"

  - name: convert list into map
    vars:
      course:
      - {'key': 'name', 'value': 'ansible'}
      - {'key': 'duration', 'value': '10HR'}
      - {'key': 'trainer', 'value': 'sivakumar'}
      - {'key': 'student', 'value': 'kranthikumar'}
    ansible.builtin.debug:
      msg: "Course Info: {{ course | items2dict  }}"

  - name: convert to uppercase
    vars:
      name: "Kranthi Kumar B"
    ansible.builtin.debug:
      msg: "Hello {{ name | upper }}"

  - name: convert to lowercase
    vars:
      name: "Kranthi Kumar B"
    ansible.builtin.debug:
      msg: "Hello {{ name | lower }}"

  - name: check IP address is valid or not
    vars:
      ip: "54.226.233.15"
    ansible.builtin.debug:
      msg: "{{ ip | ansible.utils.ipaddr }}"