- name: shell vs command
  hosts: frontend
  tasks:
  - name: redirect ls output to a file
    #ansible.builtin.command: "ls -ltr > /tmp/output.txt" by using ansible.builtin.shell only we can redirect output into a test file
    ansible.builtin.shell: "ls -ltr > /tmp/output.txt"
    register: command_result

  - name: print the outcome
    ansible.builtin.debug:
      msg: "{{ command_result }}"

  - name: redirect ls output to a file using command
    ansible.builtin.command: "ls -ltr"
    #ansible.builtin.shell: "ls -ltr > /tmp/output.txt" if you are using ansible.builtin.command only we can store the output by using "register" keyword
    register: command_output
  
  - name: print the output
    ansible.builtin.debug:
      msg: "{{ command_output }}"